# Generated by Django 6.0.7 on 2026-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2),
            preserve_default=False,
        ),
    ]
