# Generated by Django 6.0.7 on 2026-07-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
    ]
