# Generated by Django 6.0.7 on 2026-07-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff_address_remove_staff_dob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='qualification',
        ),
    ]
