# Generated by Django 6.0.7 on 2026-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['programme', 'course', 'year', 'section']},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='programme',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.CharField(choices=[('I', 'I Year'), ('II', 'II Year'), ('III', 'III Year'), ('PG-I', 'PG I Year'), ('PG-II', 'PG II Year')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'programme', 'year', 'section')},
        ),
    ]
