# Generated by Django 6.0.7 on 2026-08-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_alter_section_options_alter_section_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.CharField(choices=[('I', 'I Year'), ('II', 'II Year'), ('III', 'III Year'), ('IV', 'IV Year'), ('PG-I', 'PG I Year'), ('PG-II', 'PG II Year')], max_length=10),
        ),
    ]
