# Generated by Django 6.0.7 on 2026-08-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0003_alter_section_year'),
        ('staff', '0004_alter_staff_options_alter_staff_name_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='study_materials/')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('DOC', 'Document'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='PDF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='section.section')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='staff.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='subject.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
