# Generated by Django 6.0.7 on 2026-09-24 07:51

import study_material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(max_length=255, upload_to=study_material.models.study_material_upload_path),
        ),
    ]
