# Generated by Django 6.0.7 on 2026-08-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0003_alter_section_year'),
        ('staff', '0004_alter_staff_options_alter_staff_name_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('period', models.CharField(choices=[('1', 'Period 1'), ('2', 'Period 2'), ('3', 'Period 3'), ('4', 'Period 4'), ('5', 'Period 5'), ('6', 'Period 6')], max_length=10)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='section.section')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='staff.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='subject.subject')),
            ],
            options={
                'ordering': ['day', 'period'],
                'constraints': [models.UniqueConstraint(fields=('section', 'day', 'period'), name='unique_section_day_period')],
            },
        ),
    ]
