# Generated by Django 6.0.7 on 2026-08-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
    ]
