# Generated by Django 6.0.7 on 2026-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate')], default='UG', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('I', 'I Year'), ('II', 'II Year'), ('III', 'III Year')], max_length=5),
        ),
    ]
