# Generated by Django 6.0.7 on 2026-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_programme_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('I', 'I Year'), ('II', 'II Year'), ('III', 'III Year'), ('PG-I', 'PG I Year'), ('PG-II', 'PG II Year')], max_length=5),
        ),
    ]
