# Generated by Django 6.0.7 on 2026-09-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learning_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10),
        ),
    ]
