# Generated by Django 6.0.7 on 2026-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dean_name',
            field=models.CharField(default='Not Assigned', max_length=100),
            preserve_default=False,
        ),
    ]
