# Generated by Django 6.0.7 on 2026-09-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_dean_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone',
        ),
    ]
